### ISSUE TITLE
(Feature) List of whitelisted participants addresses

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/ico#9]
**Problem:** Since `earlyParticipantWhitelist` is mapping, we can't get the list of whitelisted participants on ICO Wizard side.
**Solution:** make changes in `CrowdsaleExt` contract
- Add public array of whitelisted addresses:
`address[] public whitelistedParticipants;`
- Extend function `setEarlyParicipantWhitelist` with filling `whitelistedParticipants` array.

Thus, we will be able to iterate through whitelisted participants on dApp side.

**Comment by fvictorio** [comment]
Starting work on this.
